DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS task;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT 0,
  password TEXT NOT NULL,
  pub_id TEXT UNIQUE NOT NULL
);

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status TEXT NOT NULL,
  due_date DATE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL
);
